name: MagicPod Test Workflow
on: workflow_dispatch

jobs:
  magic_pod_job:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Batch run test
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGICPOD_API_TOKEN }}
        run: |
          bash run_magicpod_test.sh

        
